CREATE DATABASE UrlShortenerDB;
GO

USE UrlShortenerDB;
GO

CREATE TABLE Urls
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ShortCode NVARCHAR(12) NOT NULL UNIQUE,
    LongUrl NVARCHAR(2083) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETUTCDATE(),
    LastAccessedAt DATETIME NULL,
    Clicks INT NOT NULL DEFAULT 0
);
GO

ALTER TABLE Urls
ADD CONSTRAINT CHK_LongUrl_Format CHECK (LongUrl LIKE 'http%');
GO

ALTER TABLE Urls
ADD ExpiresAt DATETIME2 NULL;

ALTER TABLE Urls
ADD IsActive BIT NOT NULL CONSTRAINT DF_Urls_IsActive DEFAULT 1;

ALTER TABLE Urls
ADD QrCodePath NVARCHAR(255) NULL;

CREATE UNIQUE INDEX IDX_Urls_ShortCode ON Urls(ShortCode);
GO

CREATE INDEX IDX_Urls_CreatedAt ON Urls(CreatedAt);
GO

CREATE TABLE UrlAccessLogs
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UrlId INT NOT NULL,
    AccessedAt DATETIME NOT NULL DEFAULT GETUTCDATE(),
    IpAddress NVARCHAR(45) NOT NULL,
    UserAgent NVARCHAR(512) NOT NULL,
    FOREIGN KEY (UrlId) REFERENCES Urls(Id)
);

CREATE INDEX IDX_UrlAccessLogs_UrlId ON UrlAccessLogs(UrlId);